version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: maintenance_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maintenance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - maintenance_network

  redis:
    image: redis:7.4-alpine
    container_name: maintenance_redis
    ports:
      - "6379:6379"
    networks:
      - maintenance_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: maintenance_backend
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maintenance_db
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - maintenance_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: maintenance_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - maintenance_network

volumes:
  postgres_data:

networks:
  maintenance_network:
    driver: bridge