version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: maintenance_postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maintenance_db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4-alpine
    container_name: maintenance_redis_dev
    ports:
      - "6379:6379"

volumes:
  postgres_data_dev: